# a training:
i.e. a matrix:

[[1,2],[1,2],[3,2]] -> [1,2] 



In [6]:
import numpy as np
arr = np.array([[1,2],[1,2],[3,2]])

In [8]:
arr[:,0]

array([1, 1, 3])

In [10]:
np.bincount(arr[:,0])

array([0, 2, 0, 1])

In [17]:
unique, counts = np.unique(arr[:,0], return_counts=True)

In [18]:
unique

array([1, 3])

In [19]:
counts

array([2, 1])